### ISSUE TITLE
Is automatic live renewal already working?

### ISSUE THREAD

**Issue by roman01la** [Daplie/node-letsencrypt#11]
Hello! Thank you for this module! I see in the readme it says that automatic live renewal is in development, but there's an example later in the code. Is it done or is it just renewal on startup?

**Comment by coolaj86** [comment]
Hello to you! You are welcome.

I did complete the live renewal. I moved that code to https://github.com/Daplie/letsencrypt-express

**Comment by coolaj86** [comment]
There's also a web management interface that I believe is functionally complete, but wasn't able to fully test yet (had to get on a flight):

## Install

```bash
npm install -g letsencrypt-express
```

## Usage

```bash
letsencrypt-express --help
```

### Accept Default Options

```bash
letsencrypt-express
```

Then you can visit <https://localhost.daplie.com> and add your own domain (you'll probably need to set your server ip address as `localhost.daplie.com` in `/etc/hosts` in a production environment).

When you visit the domain it *should* register at that time.

**Comment by roman01la** [comment]
That is very cool, thank you! I'm going to give it a spin in production, hope it will run smooth 😅

**Comment by coolaj86** [comment]
Closing since this is related to `letsencrypt-express` and it is working. Reopen in that repo if you have any trouble.
