### ISSUE TITLE
letsencrypt-koa

### ISSUE THREAD

**Issue by Globegitter** [Daplie/node-letsencrypt#14]
We started using koa over at our company and was just wondering if it would be possible to get a koa middleware as well?

If I do have some more time I might be able to do it myself, but thought I'd track it here for the time being.

**Comment by coolaj86** [comment]
I still have merging this on my todo list. Just wanted to check in and let you know.

**Comment by coolaj86** [comment]
Please take a look at my updated koa example and tell me if it looks good and works for you.

**Comment by coolaj86** [comment]
https://github.com/Daplie/letsencrypt-express#lets-encrypt-with-koa
