### ISSUE TITLE
Example/use without express?

### ISSUE THREAD

**Issue by jasonswearingen** [Daplie/node-letsencrypt#16]
Is there a way to use this without express?

I use hapi, so if there is an example of how to get/renew the cert and where its stored on disk that would solve this request

**Comment by jasonswearingen** [comment]
Ok, the docs are not super clear but looks like i need to look at the cli project

**Comment by coolaj86** [comment]
Actually, letsencrypt-express has zero dependency whatsoever on express. It relies solely on the http module and I only called that for seo.

It's what you want. This module is even lower level, but you are correct that the docs are not as clear as they need to be.

**Comment by coolaj86** [comment]
Heads up, v2 is out: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
