### ISSUE TITLE
node-letsencrypt and manually mode?

### ISSUE THREAD

**Issue by raphaelokon** [Daplie/node-letsencrypt#20]
Hi. Can I use node-letsencrypt to manually issues certs?

**Comment by coolaj86** [comment]
Yes!

See https://github.com/Daplie/letsencrypt-cli

**Comment by coolaj86** [comment]
Heads up, v2 is out: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
