### ISSUE TITLE
Do the examples work?

### ISSUE THREAD

**Issue by Analogreality** [Daplie/node-letsencrypt#21]
Do the examples work currently?

I know the API has a lot of flux, but I was just wondering if the example (serve.js) worked for anyone else.

I'm getting a
_Unhandled rejection TypeError: undefined is not a function_
error when attempting to invoke it as-is.

**Comment by coolaj86** [comment]
I completely forgot to update examples in the examples folder. In theory they should work, but I'll have to go back through and check on them.

The examples given in the README should all work currently though.

**Comment by Analogreality** [comment]
Can you please make sure they work? I.. I am not sure if I am doing
something wrong with file permissions or that sorta thing.

I love the LE concept and it is awesome you are making such a useful
mechanization to quickly attach to it. I'm just still trying to learn the
proper structure.

Thanks for your help though, awesome project btw!
On Apr 18, 2016 11:40 AM, "AJ ONeal" <notifications@github.com> wrote:
>
> I completely forgot to update examples in the examples folder. In theory
they should work, but I'll have to go back through and check on them.

**Comment by coolaj86** [comment]
The examples given in the README of letsencrypt-express work currently.

I'll take a look at the ones in the example folder her now.

What's your use case? What framework (i.e. express) and platform (i.e. Digital Ocean, AWS, etc) are you working with?

**Comment by Analogreality** [comment]
My system environment is Node on Debian. I'm using the Express framework
with the intent of hooking up this Lets Encrypt module to it to allow
automatic registration.

I have a domain that I have pointed the A record to my local computer and
it correctly navigates my home network routes to hit the SSL port I have
set up for the instance on my local dev machine.

It seems to initiate the handshake, reply with the correct challenge, but
during the actual saving or retrieval it vomits. I have the error messages
on my other machine, but that's what I recall most from memory.

I was thinking, perhaps, it had something with the SNICallback not being
specified.. I've seen a few references that are a little confusing to me..
sniCb, SNICallback, sniCallback.. but I admit it might be unrelated.

**Comment by coolaj86** [comment]
Okay, well you probably don't want to use this library directly anyway. Use [letsencrypt-express](https://github.com/Daplie/letsencrypt-express) instead. The SNI callback must complete before the challenge will be issued.

Also, give me your email address, we're working on a ddns tool and I'd like to invite you to try it before it goes into public beta.

I've also been working on a more complete solution that will actually allow you to configure it with a web gui (or via files and folder in the filesystem) and just drop your express (or koa, hapi, etc) apis into folders to become accessible to your webapp on-the-fly (no restart). We want to make node.js as simple as php for new developers (but without being entirely insecure and absolutely terrible like php).

**Comment by coolaj86** [comment]
I just created this example from the README and tested that it works end-to-end:

https://github.com/Daplie/letsencrypt-express/blob/master/examples/express.js

**Comment by coolaj86** [comment]
I'm closing this comment after updating the README.md and removing the old examples. Please open back up at letsencrypt-express if you have any trouble with that. (or come back here if you find that you really need to use the lower-level api directly and have trouble)

**Comment by coolaj86** [comment]
v2 is out with a smaller codebase, better tested, and better examples: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
