### ISSUE TITLE
Hapi integration

### ISSUE THREAD

**Issue by AdriVanHoudt** [Daplie/node-letsencrypt#22]
You have Express integration, hapi integration would be awesome!

**Comment by coolaj86** [comment]
Hey, I'm working on this. Can you hit me up on Skype coolaj86 and help me out? I'm not very familiar with hapi and I think I found the examples I need, but I'd love some help.

**Comment by coolaj86** [comment]
Take a look at https://github.com/Daplie/letsencrypt-hapi and let me know if that works for you.

**Comment by AdriVanHoudt** [comment]
you can find me (and more experienced hapi people) over at https://gitter.im/hapijs/hapi ;)
I will check this out, and help make it work, once I need to recert but I am a little bit hort on time right now

**Comment by coolaj86** [comment]
Alright, I'm going to close this issue out then. Reopen over on the other repo if you need more instruction or help.

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by coolaj86** [comment]
Heads up, v2 is out: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
