### ISSUE TITLE
Running --standalone with a webserver already running produces unclear error

### ISSUE THREAD

**Issue by GLaDOSDan** [Daplie/node-letsencrypt#24]
Running `letsencrypt --standalone` when port 80 is already in use produces the following:

	events.js:85
    
      throw er; // Unhandled 'error' event
    
            ^
	
	Error: listen EADDRINUSE

A quick skim over this (and admittedly little knowledge of exception handling in Node) caused me to initially assume this was an internal error. Perhaps a clearer error message could be displayed if node-letsencrypt can't bind to port 80?

**Comment by andrebonna** [comment]
Had the same problem here, even with parameters --http-01-port --http-01-port set to other ports

**Comment by coolaj86** [comment]
I'm moving this discussion to https://github.com/Daplie/letsencrypt-cli/issues/17

I published v2 of node-letsencrypt today, so I'll follow up with this shortly.
