### ISSUE TITLE
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED

### ISSUE THREAD

**Issue by wmhilton** [Daplie/node-letsencrypt#27]
I keep getting this error the very first time I visit my page after a clean install. (using letsencrypt-express, working on my continuous-deployment pipeline)

    [LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)

https://github.com/Daplie/node-letsencrypt/blob/master/lib/core.js#L241

**Comment by arypurnomoz** [comment]
I also got this problem. Should i worry if i use it on production?

**Comment by coolaj86** [comment]
It's benign. Also fixed as of the latest version (about to be published).

**Comment by coolaj86** [comment]
Completely fixed in v2: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
