### ISSUE TITLE
Wrapping console.warn/console.error under a logging flag?

### ISSUE THREAD

**Issue by mcav** [Daplie/node-letsencrypt#28]
While the `console.log()` calls are thoroughly wrapped behind the `opts.debug` flag, the `console.warn()` and `console.error()` messages are not. As a consumer of node-letsencrypt, it would be nice if we could also have the ability to silence or intercept the warning and error output as well, so that we can emit it as part of our own application's structured logging (rather than being sent directly to stdout).

I'd be happy to provide a PR if you agree and have a preferred way to implement this. Some options:

- Put `console.warn` and `console.error` behind `opts.debug`
- A separate logging guard like `opts.silent`
- Wrapping logging calls so that they can be explicitly intercepted/handled

Thoughts?

**Comment by Seikho** [comment]
This has been an issue in my own application as well. Despite handling the errors in callbacks, the errors still bubble and bypass my own internal logging. I've left the `console.warn` calls alone for now.

**Comment by mcav** [comment]
For now, we're using this somewhat invasive workaround:

```js
['debug', 'log', 'warn', 'error'].forEach((method) => {
  let originalFn = console[method];
  console[method] = function () {
    if (/letsencrypt\/lib/.test(new Error().stack)) {
      // log things with your own logging system
    } else {
      originalFn.apply(console, arguments);
    }
  };
});
```

**Comment by coolaj86** [comment]
This will be resolved with v2 which I'm currently testing and will push as soon as it's ready.

https://github.com/Daplie/node-letsencrypt/tree/v2.x

**Comment by coolaj86** [comment]
Completely fixed in v2: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
