### ISSUE TITLE
Bug in default setChallenge function in lib/core.js ?

### ISSUE THREAD

**Issue by jclevy** [Daplie/node-letsencrypt#30]
You may have forgotten to remove:

            args.domains = [domain];
            args.webrootPath = args.webrootPath;

in lib/core.js

    setChallenge: function (domain, key, value, done) {
            var copy = merge(defaults, { domains: [domain] });
            tplCopy(copy);

            args.domains = [domain];
            args.webrootPath = args.webrootPath;
            if (4 === handlers.setChallenge.length) {
              handlers.setChallenge(copy, key, value, done);
            }
            else if (5 === handlers.setChallenge.length) {
              handlers.setChallenge(copy, domain, key, value, done);
            }
            else {
              done(new Error("handlers.setChallenge receives the wrong number of arguments"));
            }
          }

This leads to modify the `args` content that will be used in the following `writeCertificateAsync`

In a request with multiple domains, the certificate will be written in a file having the name of the last domain specified in the original `args` array, instead of the name of the first one.

**Comment by coolaj86** [comment]
Perhaps it should be this?

```javascript
args.domains = args.domains || [domain];
```

Just do a little testing and send me a PR and I'll accept it if you tell me you know it works.

**Comment by coolaj86** [comment]
I don't currently support multiple domains with the python config file, but I'd accept a PR that updates the relevant parts of the code to make that happen.

Assuming you always list the domains in the same order it might *just work*, but I doubt it. To handle multiple domains properly you need to have a database to lookup which group of domains any particular domain belongs to so that they all **renew** at once.

**Comment by coolaj86** [comment]
This is being fixed in v2 which will be available shortly (probably later today).

You can preview the new API here:

https://github.com/Daplie/node-letsencrypt/blob/v2.x

**Comment by coolaj86** [comment]
bad link. here's the right one https://github.com/Daplie/node-letsencrypt/tree/v2.x

**Comment by coolaj86** [comment]
Completely fixed in v2: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests

**Comment by jclevy** [comment]
Thank you for the fix in v2. I'll check it in my project and let you know.
