### ISSUE TITLE
Normalize CRLF

### ISSUE THREAD

**Issue by coolaj86** [Daplie/node-letsencrypt#34]
Just need to do this:

* [ ] `fullchain = cert + "\r\n" + chain`

As per Daplie/letsencrypt-cli#8 and https://github.com/Daplie/letiny-core/issues/11

**Comment by coolaj86** [comment]
Closed https://github.com/Daplie/letiny-core/issues/11

**Comment by Seikho** [comment]
Would node's `os.EOL` constant help here?

**Comment by coolaj86** [comment]
Nope. `os.EOL` is platform specific. The problem was that there were places in the code where `\n` was used instead of `\r\n` and also that the PEM files were not properly terminated with a trailing newline. That's all fixed in v2 that I'm testing now and pushing as soon as the tests are complete and passing.

**Comment by coolaj86** [comment]
https://github.com/Daplie/node-letsencrypt/tree/v2.x

**Comment by coolaj86** [comment]
Version 2.x is now available: https://github.com/Daplie/node-letsencrypt

I did test it. https://github.com/Daplie/node-letsencrypt/tree/master/tests
