### ISSUE TITLE
Easy: allow challenge.get to be undefined [JS]

### ISSUE THREAD

**Issue by coolaj86** [Daplie/node-letsencrypt#41]
This JavaScript at [index.js line 122](https://github.com/Daplie/node-letsencrypt/blob/master/index.js#L122) needs to change so that `le.challenge.get` is allowed to be `undefined`.

* [ ] change index.js at or around line 122
* [ ] double check that `lib/core.js` doesn't make use of `le.challenge.get`

See [First Timers Only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455#.frn0zyjz7) to see why this is labeled `first-timers-only`.

**Comment by amelja** [comment]
Are you sure you don't mean the evaluation of le.store.create?

**Comment by amelja** [comment]
@coolaj86 are you sure you meant `le.challenge.get` rather than `le.store.create` which is refrenced at line 122?

**Comment by coolaj86** [comment]
Line numbers have changed. It's now around L257 https://github.com/Daplie/node-letsencrypt/blob/master/index.js#L257

**Comment by coolaj86** [comment]
@amelja did you see my comments on your pull request?

Can you make that change? I so I'll pull it in and publish a new version.

**Comment by coolaj86** [comment]
Published https://github.com/Daplie/node-letsencrypt/pull/49 in v2.1.7
