### ISSUE TITLE
Unable to handle empty cert

### ISSUE THREAD

**Issue by kievechua** [Daplie/node-letsencrypt#52]
I was testing this example 
https://github.com/Daplie/letsencrypt-express/blob/master/examples/simple.js
But my domain are unapproved.
https://github.com/Daplie/node-letsencrypt/blob/master/index.js#L201
Since nothing pass back as second parameter.
Everything in results on this line will throw error.
https://github.com/Daplie/node-letsencrypt/blob/master/index.js#L211

**Comment by coolaj86** [comment]
Thank you very much.

Fixed in v2.1.6
