### ISSUE TITLE
Vunerabilty in le-acme-core

### ISSUE THREAD

**Issue by Lily418** [Daplie/node-letsencrypt#53]
le-acme-core is using an old version of request which is using a version of tough-cookie which is affected by this issue

https://nodesecurity.io/advisories/130

I wanted to make a PR to le-acme-core but the tests are out of date and I don't know much about the library to have confidence that I could ensure that didn't have any unintended side effects. I've opened this issue so any upvotes / help is appreciated

https://github.com/Daplie/le-acme-core

**Comment by coolaj86** [comment]
Hey @Lily418, Thanks for notifying me. We don't actually use cookies (that's a security vulnerability in of itself!) so we're safe, but I'll go update the dependency anyway.
