### ISSUE TITLE
bootstrap the acme challenge dir

### ISSUE THREAD

**Issue by Pomax** [Daplie/node-letsencrypt#6]
https://github.com/Daplie/node-letsencrypt/blob/master/examples/express-minimal.js#L7 relies on a dir that "you need to make", but this can be bootstrapped automatically using the [`mkdirp`](https://www.npmjs.com/package/mkdirp) module so that people don't need to do this themselves (or you can use [`fs-extra`](as well as `rimraf`, `mkdirp`, and ) which is a drop in replacement for loading `fs`, extended with the common rm, cp and mkdir commands)

**Comment by coolaj86** [comment]
Agreed.

* Rectified in [letsencrypt-cli](https://github.com/Daplie/node-letsencrypt-cli) at [lib/webroot.js](https://github.com/Daplie/node-letsencrypt-cli/blob/master/lib/webroot.js#L14)

I'm separating some of the code into separate modules. I'll come back to close this when the main repo has those changes.

**Comment by Pomax** [comment]
cool, cheers!

**Comment by coolaj86** [comment]
I believe this is all fixed now. Reopen if you have any issues.
