### ISSUE TITLE
check actual certificate lifetime / expiresAt

### ISSUE THREAD

**Issue by coolaj86** [Daplie/node-letsencrypt#7]
currently we assume 90 days from the `mtime` of the certificate file, but that information shouldn't be too hard to extract from the certificate.

**Comment by Rush** [comment]
[http-master](https://github.com/virtkick/http-master) does it through [x509.js](https://github.com/encharm/x509.js)

**Comment by rmhrisk** [comment]
Another library (mine) would be https://github.com/GlobalSign/PKI.js/

Ryan Hurst

**Comment by Rush** [comment]
@rmhrisk nice, gonna check out PKI.js - it looks very legit. x509.js is more of a hack (it's emscripten compiled openssl with dead-code eliminated towards decoding x509)

**Comment by rmhrisk** [comment]
Our goal is to create a isomorphic pure library for all things related to x509, feedback and pull requests appreciated.

Ryan Hurst

**Comment by coolaj86** [comment]
Hey @rmhrisk, I'm finally getting around to implementing this but I'm having some trouble. I'm going to open an issue over at your repo to ask for some help.

**Comment by rmhrisk** [comment]
Yury will respond to your bug tonight.

**Comment by coolaj86** [comment]
Got it working:

```javascript
'use strict';

var merge = require("node.extend");

var common = require("asn1js/org/pkijs/common");
var _asn1js = require("asn1js");
var _pkijs = require("pkijs");
var _x509schema = require("pkijs/org/pkijs/x509_schema");

// #region Merging function/object declarations for ASN1js and PKIjs
var asn1js = merge(true, _asn1js, common);

var x509schema = merge(true, _x509schema, asn1js);

var pkijs_1 = merge(true, _pkijs, asn1js);
var pkijs = merge(true, pkijs_1, x509schema);

var pem = require('fs').readFileSync('./example.cert.pem', 'ascii');
var b64 = pem.replace(/(-----(BEGIN|END) CERTIFICATE-----|[\n\r])/g, '');
var buf = Buffer(b64, 'base64');
var ab = new Uint8Array(buf).buffer;          // WORKS
//var ab = buf.buffer                         // Doesn't work
console.log(ab);
var asn1 = pkijs.org.pkijs.fromBER(ab);
var cert_simpl = new pkijs.org.pkijs.simpl.CERT({ schema: asn1.result });

console.log(cert_simpl);
```

**Comment by coolaj86** [comment]
It pains me how expensive it is to get this information... ugh...

It's 1.1mb minified JavaScript with x509.js and still about ~500kb minified using PKI.js.

That's **a lot** of of memory consumption for such a tiny tiny task. This has to run on systems that have as little as 256mb of memory.

Lamenting, but closed. https://github.com/Daplie/node-letsencrypt/commit/61ddeba8e27eacc1243218b983367d47285c96d2 https://github.com/Daplie/node-letsencrypt/commit/baec7ed5c312fb06ea5aeb935392c1e06e62a745

**Comment by Rush** [comment]
Wow, why is PKI.js so large? x509.js is large because of emscripten so no wonder. :) Also I'm curious what's the performance of x509.js vs PKI.js - but it probably hardly matters in node-letsencrypt? x509.js's performance is around 50% of openssl's binary performance.

**Comment by rmhrisk** [comment]
The ES6 version of PKIjs is more modular and when combined with tree shaking (assuming all dependencies are ES6) it would be even smaller.

**Comment by rmhrisk** [comment]
PKIjs implements all related X509 standards and not just certificate parsing; this is why it is as large as it is.
